/*"W.A.J. P to demonstrate try catch block, 
  Take two numbers from the user and perform the division operation and handle Arithmetic Exception. 
  O/P- Enter two numbers: 10 0
Exception in thread main java.lang.ArithmeticException:/ by zero"
 */

package assignment;

import java.util.Scanner;

public class A36 {
	
	public static void main(String[] args) {
		
		int num1=10,num2=0,result;
		
		try {
			result=num1/num2;
			System.out.println("Rsult : "+ result);
		}
		catch (ArithmeticException e) {
			System.out.println("Number cannot divided by zero");
		}
	}
}
