/*"W.A.J. P to demonstrate try catch block, 
  Take two numbers from the user and perform the division operation and handle Arithmetic Exception. 
  O/P- Enter two numbers: 10 0
Exception in thread main java.lang.ArithmeticException:/ by zero"
 */

package assignment;

import java.util.Scanner;

public class A36 {
	
	public static void main(String[] args) {
		
		Scanner sc=new Scanner(System.in);
		int num1,num2,result;
		
		
		
		try {
			System.out.println("Enter two numbers : ");
			num1=sc.nextInt();
			num2=sc.nextInt();
			result=num1/num2;
			
			System.out.println("Rsult : "+ result);
		}catch (Exception e) {
			System.out.println("Cannot divided by zero");
		}
	}
}
